// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: debug.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "debug.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace protocol {
namespace debug {

namespace {

const ::google::protobuf::Descriptor* DebugRequest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DebugRequest_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_debug_2eproto() {
  protobuf_AddDesc_debug_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "debug.proto");
  GOOGLE_CHECK(file != NULL);
  DebugRequest_descriptor_ = file->message_type(0);
  static const int DebugRequest_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DebugRequest, originmodule_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DebugRequest, originmethod_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DebugRequest, requestdata_),
  };
  DebugRequest_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      DebugRequest_descriptor_,
      DebugRequest::default_instance_,
      DebugRequest_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DebugRequest, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DebugRequest, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(DebugRequest));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_debug_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    DebugRequest_descriptor_, &DebugRequest::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_debug_2eproto() {
  delete DebugRequest::default_instance_;
  delete DebugRequest_reflection_;
}

void protobuf_AddDesc_debug_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\013debug.proto\022\016protocol.debug\"O\n\014DebugRe"
    "quest\022\024\n\014originModule\030\001 \002(\t\022\024\n\014originMet"
    "hod\030\002 \002(\t\022\023\n\013requestData\030\003 \002(\014", 110);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "debug.proto", &protobuf_RegisterTypes);
  DebugRequest::default_instance_ = new DebugRequest();
  DebugRequest::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_debug_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_debug_2eproto {
  StaticDescriptorInitializer_debug_2eproto() {
    protobuf_AddDesc_debug_2eproto();
  }
} static_descriptor_initializer_debug_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int DebugRequest::kOriginModuleFieldNumber;
const int DebugRequest::kOriginMethodFieldNumber;
const int DebugRequest::kRequestDataFieldNumber;
#endif  // !_MSC_VER

DebugRequest::DebugRequest()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void DebugRequest::InitAsDefaultInstance() {
}

DebugRequest::DebugRequest(const DebugRequest& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void DebugRequest::SharedCtor() {
  _cached_size_ = 0;
  originmodule_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  originmethod_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  requestdata_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

DebugRequest::~DebugRequest() {
  SharedDtor();
}

void DebugRequest::SharedDtor() {
  if (originmodule_ != &::google::protobuf::internal::kEmptyString) {
    delete originmodule_;
  }
  if (originmethod_ != &::google::protobuf::internal::kEmptyString) {
    delete originmethod_;
  }
  if (requestdata_ != &::google::protobuf::internal::kEmptyString) {
    delete requestdata_;
  }
  if (this != default_instance_) {
  }
}

void DebugRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DebugRequest::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DebugRequest_descriptor_;
}

const DebugRequest& DebugRequest::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_debug_2eproto();
  return *default_instance_;
}

DebugRequest* DebugRequest::default_instance_ = NULL;

DebugRequest* DebugRequest::New() const {
  return new DebugRequest;
}

void DebugRequest::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_originmodule()) {
      if (originmodule_ != &::google::protobuf::internal::kEmptyString) {
        originmodule_->clear();
      }
    }
    if (has_originmethod()) {
      if (originmethod_ != &::google::protobuf::internal::kEmptyString) {
        originmethod_->clear();
      }
    }
    if (has_requestdata()) {
      if (requestdata_ != &::google::protobuf::internal::kEmptyString) {
        requestdata_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool DebugRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string originModule = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_originmodule()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->originmodule().data(), this->originmodule().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_originMethod;
        break;
      }

      // required string originMethod = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_originMethod:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_originmethod()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->originmethod().data(), this->originmethod().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_requestData;
        break;
      }

      // required bytes requestData = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_requestData:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_requestdata()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void DebugRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string originModule = 1;
  if (has_originmodule()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->originmodule().data(), this->originmodule().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->originmodule(), output);
  }

  // required string originMethod = 2;
  if (has_originmethod()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->originmethod().data(), this->originmethod().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->originmethod(), output);
  }

  // required bytes requestData = 3;
  if (has_requestdata()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      3, this->requestdata(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* DebugRequest::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string originModule = 1;
  if (has_originmodule()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->originmodule().data(), this->originmodule().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->originmodule(), target);
  }

  // required string originMethod = 2;
  if (has_originmethod()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->originmethod().data(), this->originmethod().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->originmethod(), target);
  }

  // required bytes requestData = 3;
  if (has_requestdata()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        3, this->requestdata(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int DebugRequest::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string originModule = 1;
    if (has_originmodule()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->originmodule());
    }

    // required string originMethod = 2;
    if (has_originmethod()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->originmethod());
    }

    // required bytes requestData = 3;
    if (has_requestdata()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->requestdata());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DebugRequest::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const DebugRequest* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const DebugRequest*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void DebugRequest::MergeFrom(const DebugRequest& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_originmodule()) {
      set_originmodule(from.originmodule());
    }
    if (from.has_originmethod()) {
      set_originmethod(from.originmethod());
    }
    if (from.has_requestdata()) {
      set_requestdata(from.requestdata());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void DebugRequest::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DebugRequest::CopyFrom(const DebugRequest& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DebugRequest::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void DebugRequest::Swap(DebugRequest* other) {
  if (other != this) {
    std::swap(originmodule_, other->originmodule_);
    std::swap(originmethod_, other->originmethod_);
    std::swap(requestdata_, other->requestdata_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata DebugRequest::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = DebugRequest_descriptor_;
  metadata.reflection = DebugRequest_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace debug
}  // namespace protocol

// @@protoc_insertion_point(global_scope)
