// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: debug.proto

#ifndef PROTOBUF_debug_2eproto__INCLUDED
#define PROTOBUF_debug_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protocol {
namespace debug {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_debug_2eproto();
void protobuf_AssignDesc_debug_2eproto();
void protobuf_ShutdownFile_debug_2eproto();

class DebugRequest;
class DebugResponse;

// ===================================================================

class DebugRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:protocol.debug.DebugRequest) */ {
 public:
  DebugRequest();
  virtual ~DebugRequest();

  DebugRequest(const DebugRequest& from);

  inline DebugRequest& operator=(const DebugRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DebugRequest& default_instance();

  void Swap(DebugRequest* other);

  // implements Message ----------------------------------------------

  inline DebugRequest* New() const { return New(NULL); }

  DebugRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DebugRequest& from);
  void MergeFrom(const DebugRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(DebugRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string originModule = 1;
  bool has_originmodule() const;
  void clear_originmodule();
  static const int kOriginModuleFieldNumber = 1;
  const ::std::string& originmodule() const;
  void set_originmodule(const ::std::string& value);
  void set_originmodule(const char* value);
  void set_originmodule(const char* value, size_t size);
  ::std::string* mutable_originmodule();
  ::std::string* release_originmodule();
  void set_allocated_originmodule(::std::string* originmodule);

  // required string originMethod = 2;
  bool has_originmethod() const;
  void clear_originmethod();
  static const int kOriginMethodFieldNumber = 2;
  const ::std::string& originmethod() const;
  void set_originmethod(const ::std::string& value);
  void set_originmethod(const char* value);
  void set_originmethod(const char* value, size_t size);
  ::std::string* mutable_originmethod();
  ::std::string* release_originmethod();
  void set_allocated_originmethod(::std::string* originmethod);

  // required bytes requestData = 3;
  bool has_requestdata() const;
  void clear_requestdata();
  static const int kRequestDataFieldNumber = 3;
  const ::std::string& requestdata() const;
  void set_requestdata(const ::std::string& value);
  void set_requestdata(const char* value);
  void set_requestdata(const void* value, size_t size);
  ::std::string* mutable_requestdata();
  ::std::string* release_requestdata();
  void set_allocated_requestdata(::std::string* requestdata);

  // @@protoc_insertion_point(class_scope:protocol.debug.DebugRequest)
 private:
  inline void set_has_originmodule();
  inline void clear_has_originmodule();
  inline void set_has_originmethod();
  inline void clear_has_originmethod();
  inline void set_has_requestdata();
  inline void clear_has_requestdata();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr originmodule_;
  ::google::protobuf::internal::ArenaStringPtr originmethod_;
  ::google::protobuf::internal::ArenaStringPtr requestdata_;
  friend void  protobuf_AddDesc_debug_2eproto();
  friend void protobuf_AssignDesc_debug_2eproto();
  friend void protobuf_ShutdownFile_debug_2eproto();

  void InitAsDefaultInstance();
  static DebugRequest* default_instance_;
};
// -------------------------------------------------------------------

class DebugResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:protocol.debug.DebugResponse) */ {
 public:
  DebugResponse();
  virtual ~DebugResponse();

  DebugResponse(const DebugResponse& from);

  inline DebugResponse& operator=(const DebugResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DebugResponse& default_instance();

  void Swap(DebugResponse* other);

  // implements Message ----------------------------------------------

  inline DebugResponse* New() const { return New(NULL); }

  DebugResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DebugResponse& from);
  void MergeFrom(const DebugResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(DebugResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 respStatus = 1;
  bool has_respstatus() const;
  void clear_respstatus();
  static const int kRespStatusFieldNumber = 1;
  ::google::protobuf::int32 respstatus() const;
  void set_respstatus(::google::protobuf::int32 value);

  // required string debugMessage = 2;
  bool has_debugmessage() const;
  void clear_debugmessage();
  static const int kDebugMessageFieldNumber = 2;
  const ::std::string& debugmessage() const;
  void set_debugmessage(const ::std::string& value);
  void set_debugmessage(const char* value);
  void set_debugmessage(const char* value, size_t size);
  ::std::string* mutable_debugmessage();
  ::std::string* release_debugmessage();
  void set_allocated_debugmessage(::std::string* debugmessage);

  // required bytes responseData = 3;
  bool has_responsedata() const;
  void clear_responsedata();
  static const int kResponseDataFieldNumber = 3;
  const ::std::string& responsedata() const;
  void set_responsedata(const ::std::string& value);
  void set_responsedata(const char* value);
  void set_responsedata(const void* value, size_t size);
  ::std::string* mutable_responsedata();
  ::std::string* release_responsedata();
  void set_allocated_responsedata(::std::string* responsedata);

  // @@protoc_insertion_point(class_scope:protocol.debug.DebugResponse)
 private:
  inline void set_has_respstatus();
  inline void clear_has_respstatus();
  inline void set_has_debugmessage();
  inline void clear_has_debugmessage();
  inline void set_has_responsedata();
  inline void clear_has_responsedata();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr debugmessage_;
  ::google::protobuf::internal::ArenaStringPtr responsedata_;
  ::google::protobuf::int32 respstatus_;
  friend void  protobuf_AddDesc_debug_2eproto();
  friend void protobuf_AssignDesc_debug_2eproto();
  friend void protobuf_ShutdownFile_debug_2eproto();

  void InitAsDefaultInstance();
  static DebugResponse* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// DebugRequest

// required string originModule = 1;
inline bool DebugRequest::has_originmodule() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DebugRequest::set_has_originmodule() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DebugRequest::clear_has_originmodule() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DebugRequest::clear_originmodule() {
  originmodule_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_originmodule();
}
inline const ::std::string& DebugRequest::originmodule() const {
  // @@protoc_insertion_point(field_get:protocol.debug.DebugRequest.originModule)
  return originmodule_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DebugRequest::set_originmodule(const ::std::string& value) {
  set_has_originmodule();
  originmodule_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:protocol.debug.DebugRequest.originModule)
}
inline void DebugRequest::set_originmodule(const char* value) {
  set_has_originmodule();
  originmodule_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protocol.debug.DebugRequest.originModule)
}
inline void DebugRequest::set_originmodule(const char* value, size_t size) {
  set_has_originmodule();
  originmodule_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protocol.debug.DebugRequest.originModule)
}
inline ::std::string* DebugRequest::mutable_originmodule() {
  set_has_originmodule();
  // @@protoc_insertion_point(field_mutable:protocol.debug.DebugRequest.originModule)
  return originmodule_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DebugRequest::release_originmodule() {
  // @@protoc_insertion_point(field_release:protocol.debug.DebugRequest.originModule)
  clear_has_originmodule();
  return originmodule_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DebugRequest::set_allocated_originmodule(::std::string* originmodule) {
  if (originmodule != NULL) {
    set_has_originmodule();
  } else {
    clear_has_originmodule();
  }
  originmodule_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), originmodule);
  // @@protoc_insertion_point(field_set_allocated:protocol.debug.DebugRequest.originModule)
}

// required string originMethod = 2;
inline bool DebugRequest::has_originmethod() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DebugRequest::set_has_originmethod() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DebugRequest::clear_has_originmethod() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DebugRequest::clear_originmethod() {
  originmethod_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_originmethod();
}
inline const ::std::string& DebugRequest::originmethod() const {
  // @@protoc_insertion_point(field_get:protocol.debug.DebugRequest.originMethod)
  return originmethod_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DebugRequest::set_originmethod(const ::std::string& value) {
  set_has_originmethod();
  originmethod_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:protocol.debug.DebugRequest.originMethod)
}
inline void DebugRequest::set_originmethod(const char* value) {
  set_has_originmethod();
  originmethod_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protocol.debug.DebugRequest.originMethod)
}
inline void DebugRequest::set_originmethod(const char* value, size_t size) {
  set_has_originmethod();
  originmethod_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protocol.debug.DebugRequest.originMethod)
}
inline ::std::string* DebugRequest::mutable_originmethod() {
  set_has_originmethod();
  // @@protoc_insertion_point(field_mutable:protocol.debug.DebugRequest.originMethod)
  return originmethod_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DebugRequest::release_originmethod() {
  // @@protoc_insertion_point(field_release:protocol.debug.DebugRequest.originMethod)
  clear_has_originmethod();
  return originmethod_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DebugRequest::set_allocated_originmethod(::std::string* originmethod) {
  if (originmethod != NULL) {
    set_has_originmethod();
  } else {
    clear_has_originmethod();
  }
  originmethod_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), originmethod);
  // @@protoc_insertion_point(field_set_allocated:protocol.debug.DebugRequest.originMethod)
}

// required bytes requestData = 3;
inline bool DebugRequest::has_requestdata() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void DebugRequest::set_has_requestdata() {
  _has_bits_[0] |= 0x00000004u;
}
inline void DebugRequest::clear_has_requestdata() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void DebugRequest::clear_requestdata() {
  requestdata_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_requestdata();
}
inline const ::std::string& DebugRequest::requestdata() const {
  // @@protoc_insertion_point(field_get:protocol.debug.DebugRequest.requestData)
  return requestdata_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DebugRequest::set_requestdata(const ::std::string& value) {
  set_has_requestdata();
  requestdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:protocol.debug.DebugRequest.requestData)
}
inline void DebugRequest::set_requestdata(const char* value) {
  set_has_requestdata();
  requestdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protocol.debug.DebugRequest.requestData)
}
inline void DebugRequest::set_requestdata(const void* value, size_t size) {
  set_has_requestdata();
  requestdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protocol.debug.DebugRequest.requestData)
}
inline ::std::string* DebugRequest::mutable_requestdata() {
  set_has_requestdata();
  // @@protoc_insertion_point(field_mutable:protocol.debug.DebugRequest.requestData)
  return requestdata_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DebugRequest::release_requestdata() {
  // @@protoc_insertion_point(field_release:protocol.debug.DebugRequest.requestData)
  clear_has_requestdata();
  return requestdata_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DebugRequest::set_allocated_requestdata(::std::string* requestdata) {
  if (requestdata != NULL) {
    set_has_requestdata();
  } else {
    clear_has_requestdata();
  }
  requestdata_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), requestdata);
  // @@protoc_insertion_point(field_set_allocated:protocol.debug.DebugRequest.requestData)
}

// -------------------------------------------------------------------

// DebugResponse

// required int32 respStatus = 1;
inline bool DebugResponse::has_respstatus() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DebugResponse::set_has_respstatus() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DebugResponse::clear_has_respstatus() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DebugResponse::clear_respstatus() {
  respstatus_ = 0;
  clear_has_respstatus();
}
inline ::google::protobuf::int32 DebugResponse::respstatus() const {
  // @@protoc_insertion_point(field_get:protocol.debug.DebugResponse.respStatus)
  return respstatus_;
}
inline void DebugResponse::set_respstatus(::google::protobuf::int32 value) {
  set_has_respstatus();
  respstatus_ = value;
  // @@protoc_insertion_point(field_set:protocol.debug.DebugResponse.respStatus)
}

// required string debugMessage = 2;
inline bool DebugResponse::has_debugmessage() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DebugResponse::set_has_debugmessage() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DebugResponse::clear_has_debugmessage() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DebugResponse::clear_debugmessage() {
  debugmessage_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_debugmessage();
}
inline const ::std::string& DebugResponse::debugmessage() const {
  // @@protoc_insertion_point(field_get:protocol.debug.DebugResponse.debugMessage)
  return debugmessage_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DebugResponse::set_debugmessage(const ::std::string& value) {
  set_has_debugmessage();
  debugmessage_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:protocol.debug.DebugResponse.debugMessage)
}
inline void DebugResponse::set_debugmessage(const char* value) {
  set_has_debugmessage();
  debugmessage_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protocol.debug.DebugResponse.debugMessage)
}
inline void DebugResponse::set_debugmessage(const char* value, size_t size) {
  set_has_debugmessage();
  debugmessage_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protocol.debug.DebugResponse.debugMessage)
}
inline ::std::string* DebugResponse::mutable_debugmessage() {
  set_has_debugmessage();
  // @@protoc_insertion_point(field_mutable:protocol.debug.DebugResponse.debugMessage)
  return debugmessage_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DebugResponse::release_debugmessage() {
  // @@protoc_insertion_point(field_release:protocol.debug.DebugResponse.debugMessage)
  clear_has_debugmessage();
  return debugmessage_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DebugResponse::set_allocated_debugmessage(::std::string* debugmessage) {
  if (debugmessage != NULL) {
    set_has_debugmessage();
  } else {
    clear_has_debugmessage();
  }
  debugmessage_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), debugmessage);
  // @@protoc_insertion_point(field_set_allocated:protocol.debug.DebugResponse.debugMessage)
}

// required bytes responseData = 3;
inline bool DebugResponse::has_responsedata() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void DebugResponse::set_has_responsedata() {
  _has_bits_[0] |= 0x00000004u;
}
inline void DebugResponse::clear_has_responsedata() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void DebugResponse::clear_responsedata() {
  responsedata_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_responsedata();
}
inline const ::std::string& DebugResponse::responsedata() const {
  // @@protoc_insertion_point(field_get:protocol.debug.DebugResponse.responseData)
  return responsedata_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DebugResponse::set_responsedata(const ::std::string& value) {
  set_has_responsedata();
  responsedata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:protocol.debug.DebugResponse.responseData)
}
inline void DebugResponse::set_responsedata(const char* value) {
  set_has_responsedata();
  responsedata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protocol.debug.DebugResponse.responseData)
}
inline void DebugResponse::set_responsedata(const void* value, size_t size) {
  set_has_responsedata();
  responsedata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protocol.debug.DebugResponse.responseData)
}
inline ::std::string* DebugResponse::mutable_responsedata() {
  set_has_responsedata();
  // @@protoc_insertion_point(field_mutable:protocol.debug.DebugResponse.responseData)
  return responsedata_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DebugResponse::release_responsedata() {
  // @@protoc_insertion_point(field_release:protocol.debug.DebugResponse.responseData)
  clear_has_responsedata();
  return responsedata_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DebugResponse::set_allocated_responsedata(::std::string* responsedata) {
  if (responsedata != NULL) {
    set_has_responsedata();
  } else {
    clear_has_responsedata();
  }
  responsedata_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), responsedata);
  // @@protoc_insertion_point(field_set_allocated:protocol.debug.DebugResponse.responseData)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace debug
}  // namespace protocol

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_debug_2eproto__INCLUDED
