// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wk_adx_rtb_ext.proto

#ifndef PROTOBUF_wk_5fadx_5frtb_5fext_2eproto__INCLUDED
#define PROTOBUF_wk_5fadx_5frtb_5fext_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include "openrtb.pb.h"
// @@protoc_insertion_point(includes)

namespace com {
namespace wk {
namespace adx {
namespace rtb {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_wk_5fadx_5frtb_5fext_2eproto();
void protobuf_AssignDesc_wk_5fadx_5frtb_5fext_2eproto();
void protobuf_ShutdownFile_wk_5fadx_5frtb_5fext_2eproto();


enum InteractionType {
  NO_INTERACTION = 0,
  SURFING = 1,
  DOWNLOAD = 2,
  EXTERNAL = 3
};
bool InteractionType_IsValid(int value);
const InteractionType InteractionType_MIN = NO_INTERACTION;
const InteractionType InteractionType_MAX = EXTERNAL;
const int InteractionType_ARRAYSIZE = InteractionType_MAX + 1;

const ::google::protobuf::EnumDescriptor* InteractionType_descriptor();
inline const ::std::string& InteractionType_Name(InteractionType value) {
  return ::google::protobuf::internal::NameOfEnum(
    InteractionType_descriptor(), value);
}
inline bool InteractionType_Parse(
    const ::std::string& name, InteractionType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<InteractionType>(
    InteractionType_descriptor(), name, value);
}
// ===================================================================


// ===================================================================

static const int kIsDebugFieldNumber = 201;
extern ::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidRequest,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  is_debug;
static const int kIsSplashScreenFieldNumber = 200;
extern ::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidRequest_Imp,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  is_splash_screen;
static const int kBitcFieldNumber = 201;
extern ::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidRequest_Imp,
    ::google::protobuf::internal::RepeatedPrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  bitc;
static const int kImptrackersFieldNumber = 200;
extern ::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidResponse_SeatBid_Bid,
    ::google::protobuf::internal::RepeatedStringTypeTraits, 9, false >
  imptrackers;
static const int kClktrackersFieldNumber = 201;
extern ::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidResponse_SeatBid_Bid,
    ::google::protobuf::internal::RepeatedStringTypeTraits, 9, false >
  clktrackers;
static const int kCreativeIdFieldNumber = 202;
extern ::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidResponse_SeatBid_Bid,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  creative_id;
static const int kTagidFieldNumber = 203;
extern ::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidResponse_SeatBid_Bid,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  tagid;
static const int kInteractionTypeFieldNumber = 204;
extern ::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidResponse_SeatBid_Bid,
    ::google::protobuf::internal::EnumTypeTraits< ::com::wk::adx::rtb::InteractionType, ::com::wk::adx::rtb::InteractionType_IsValid>, 14, false >
  interactionType;
static const int kDownloadtraceurlFieldNumber = 205;
extern ::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidResponse_SeatBid_Bid,
    ::google::protobuf::internal::RepeatedStringTypeTraits, 9, false >
  downloadtraceurl;
static const int kActivetraceurlFieldNumber = 206;
extern ::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidResponse_SeatBid_Bid,
    ::google::protobuf::internal::RepeatedStringTypeTraits, 9, false >
  activetraceurl;
static const int kDwnlstFieldNumber = 207;
extern ::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidResponse_SeatBid_Bid,
    ::google::protobuf::internal::RepeatedStringTypeTraits, 9, false >
  dwnlst;
static const int kIntltrackersFieldNumber = 208;
extern ::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidResponse_SeatBid_Bid,
    ::google::protobuf::internal::RepeatedStringTypeTraits, 9, false >
  intltrackers;

// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace rtb
}  // namespace adx
}  // namespace wk
}  // namespace com

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::com::wk::adx::rtb::InteractionType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::com::wk::adx::rtb::InteractionType>() {
  return ::com::wk::adx::rtb::InteractionType_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_wk_5fadx_5frtb_5fext_2eproto__INCLUDED
