// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wk_adx_rtb_ext.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "wk_adx_rtb_ext.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace wk {
namespace adx {
namespace rtb {

namespace {

const ::google::protobuf::EnumDescriptor* InteractionType_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_wk_5fadx_5frtb_5fext_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_wk_5fadx_5frtb_5fext_2eproto() {
  protobuf_AddDesc_wk_5fadx_5frtb_5fext_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "wk_adx_rtb_ext.proto");
  GOOGLE_CHECK(file != NULL);
  InteractionType_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_wk_5fadx_5frtb_5fext_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_wk_5fadx_5frtb_5fext_2eproto() {
}

void protobuf_AddDesc_wk_5fadx_5frtb_5fext_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_wk_5fadx_5frtb_5fext_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::com::google::openrtb::protobuf_AddDesc_openrtb_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024wk_adx_rtb_ext.proto\022\016com.wk.adx.rtb\032\r"
    "openrtb.proto*N\n\017InteractionType\022\022\n\016NO_I"
    "NTERACTION\020\000\022\013\n\007SURFING\020\001\022\014\n\010DOWNLOAD\020\002\022"
    "\014\n\010EXTERNAL\020\003:1\n\010is_debug\022\036.com.google.o"
    "penrtb.BidRequest\030\311\001 \001(\005:=\n\020is_splash_sc"
    "reen\022\".com.google.openrtb.BidRequest.Imp"
    "\030\310\001 \001(\005:1\n\004bitc\022\".com.google.openrtb.Bid"
    "Request.Imp\030\311\001 \003(\005:A\n\013imptrackers\022+.com."
    "google.openrtb.BidResponse.SeatBid.Bid\030\310"
    "\001 \003(\t:A\n\013clktrackers\022+.com.google.openrt"
    "b.BidResponse.SeatBid.Bid\030\311\001 \003(\t:A\n\013crea"
    "tive_id\022+.com.google.openrtb.BidResponse"
    ".SeatBid.Bid\030\312\001 \001(\t:;\n\005tagid\022+.com.googl"
    "e.openrtb.BidResponse.SeatBid.Bid\030\313\001 \001(\t"
    ":f\n\017interactionType\022+.com.google.openrtb"
    ".BidResponse.SeatBid.Bid\030\314\001 \001(\0162\037.com.wk"
    ".adx.rtb.InteractionType:F\n\020downloadtrac"
    "eurl\022+.com.google.openrtb.BidResponse.Se"
    "atBid.Bid\030\315\001 \003(\t:D\n\016activetraceurl\022+.com"
    ".google.openrtb.BidResponse.SeatBid.Bid\030"
    "\316\001 \003(\t:<\n\006dwnlst\022+.com.google.openrtb.Bi"
    "dResponse.SeatBid.Bid\030\317\001 \003(\t:B\n\014intltrac"
    "kers\022+.com.google.openrtb.BidResponse.Se"
    "atBid.Bid\030\320\001 \003(\tB\nB\010WkAdxExt", 948);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "wk_adx_rtb_ext.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::com::google::openrtb::BidRequest::default_instance(),
    201, 5, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::com::google::openrtb::BidRequest_Imp::default_instance(),
    200, 5, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::com::google::openrtb::BidRequest_Imp::default_instance(),
    201, 5, true, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::com::google::openrtb::BidResponse_SeatBid_Bid::default_instance(),
    200, 9, true, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::com::google::openrtb::BidResponse_SeatBid_Bid::default_instance(),
    201, 9, true, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::com::google::openrtb::BidResponse_SeatBid_Bid::default_instance(),
    202, 9, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::com::google::openrtb::BidResponse_SeatBid_Bid::default_instance(),
    203, 9, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterEnumExtension(
    &::com::google::openrtb::BidResponse_SeatBid_Bid::default_instance(),
    204, 14, false, false,
    &::com::wk::adx::rtb::InteractionType_IsValid);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::com::google::openrtb::BidResponse_SeatBid_Bid::default_instance(),
    205, 9, true, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::com::google::openrtb::BidResponse_SeatBid_Bid::default_instance(),
    206, 9, true, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::com::google::openrtb::BidResponse_SeatBid_Bid::default_instance(),
    207, 9, true, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::com::google::openrtb::BidResponse_SeatBid_Bid::default_instance(),
    208, 9, true, false);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_wk_5fadx_5frtb_5fext_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_wk_5fadx_5frtb_5fext_2eproto {
  StaticDescriptorInitializer_wk_5fadx_5frtb_5fext_2eproto() {
    protobuf_AddDesc_wk_5fadx_5frtb_5fext_2eproto();
  }
} static_descriptor_initializer_wk_5fadx_5frtb_5fext_2eproto_;
const ::google::protobuf::EnumDescriptor* InteractionType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return InteractionType_descriptor_;
}
bool InteractionType_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidRequest,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  is_debug(kIsDebugFieldNumber, 0);
::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidRequest_Imp,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  is_splash_screen(kIsSplashScreenFieldNumber, 0);
::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidRequest_Imp,
    ::google::protobuf::internal::RepeatedPrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  bitc(kBitcFieldNumber, 0);
const ::std::string imptrackers_default("");
::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidResponse_SeatBid_Bid,
    ::google::protobuf::internal::RepeatedStringTypeTraits, 9, false >
  imptrackers(kImptrackersFieldNumber, imptrackers_default);
const ::std::string clktrackers_default("");
::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidResponse_SeatBid_Bid,
    ::google::protobuf::internal::RepeatedStringTypeTraits, 9, false >
  clktrackers(kClktrackersFieldNumber, clktrackers_default);
const ::std::string creative_id_default("");
::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidResponse_SeatBid_Bid,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  creative_id(kCreativeIdFieldNumber, creative_id_default);
const ::std::string tagid_default("");
::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidResponse_SeatBid_Bid,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  tagid(kTagidFieldNumber, tagid_default);
::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidResponse_SeatBid_Bid,
    ::google::protobuf::internal::EnumTypeTraits< ::com::wk::adx::rtb::InteractionType, ::com::wk::adx::rtb::InteractionType_IsValid>, 14, false >
  interactionType(kInteractionTypeFieldNumber, static_cast< ::com::wk::adx::rtb::InteractionType >(0));
const ::std::string downloadtraceurl_default("");
::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidResponse_SeatBid_Bid,
    ::google::protobuf::internal::RepeatedStringTypeTraits, 9, false >
  downloadtraceurl(kDownloadtraceurlFieldNumber, downloadtraceurl_default);
const ::std::string activetraceurl_default("");
::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidResponse_SeatBid_Bid,
    ::google::protobuf::internal::RepeatedStringTypeTraits, 9, false >
  activetraceurl(kActivetraceurlFieldNumber, activetraceurl_default);
const ::std::string dwnlst_default("");
::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidResponse_SeatBid_Bid,
    ::google::protobuf::internal::RepeatedStringTypeTraits, 9, false >
  dwnlst(kDwnlstFieldNumber, dwnlst_default);
const ::std::string intltrackers_default("");
::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidResponse_SeatBid_Bid,
    ::google::protobuf::internal::RepeatedStringTypeTraits, 9, false >
  intltrackers(kIntltrackersFieldNumber, intltrackers_default);

// @@protoc_insertion_point(namespace_scope)

}  // namespace rtb
}  // namespace adx
}  // namespace wk
}  // namespace com

// @@protoc_insertion_point(global_scope)
